---
title: "resources"
subtitle: "a collection of other people's writings, tutorials, etc. that I find particularly helpful"
toc: true
---

## {{< fa tools >}} r tools

* [free icons from fontawesome](https://fontawesome.com/v5/search?m=free) + the [`{fontawesome}`](https://github.com/rstudio/fontawesome) R package for infusing your slides, website, RMarkdowns/Quarto Markdowns, and more with an extra splash of fun

## {{< fa chart-bar >}} data viz

* [from Data to Viz](https://www.data-to-viz.com/), a choose-your-adventure-type experience for creating your best data visualizations


## {{< fa desktop >}} reporting & presentations

* [Quarto](https://quarto.org/) supports a variety of formats for [creating presentations](https://quarto.org/docs/presentations/), including:

    - [revealjs (HTML)](https://quarto.org/docs/presentations/revealjs/)
    
    - [PowerPoint (MS Office)](https://quarto.org/docs/presentations/powerpoint.html/)
    
    - [Beamer (LaTex/PDF)](https://quarto.org/docs/presentations/beamer.html/)
    

* [Meet xaringan: Making slides in R Markdown](https://arm.rbind.io/slides/xaringan.html#1), by Allison Hill

## {{< fa book-open >}} learning materials

* Ever feel like you need a pick-me-up while learning stats or a new R tool? Look no further than [Allison Horst's](https://twitter.com/allison_horst) [Data Science Illustrations](https://allisonhorst.com/), featuring the cutest and most educational fuzzy monsters you'll ever see!

* [Mastering Shiny](https://mastering-shiny.org/index.html), by Hadley Wickham 

* [Happy Git and GitHub for the useR](https://happygitwithr.com/), by Jenny Bryan

* [R for Data Science](https://r4ds.had.co.nz/), by Hadley Wickham

* [W3Schools](https://www.w3schools.com/default.asp), particularly for their HTML & CSS tutorials

## {{< fa users >}} data science communities

## {{< fa window-maximize >}} web accessibility

* [The A11Y Project](https://www.a11yproject.com/) is a community-driven effort to make digital content more accessible. The A11Y Project not only has a ton of great blog posts, but also [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) compliance checklist.  

* [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/), a color blindness simulator -- just upload a file and view your color palettes as they would appear under different types of color deficiencies

## {{< fa smile >}} misc.

* Discover new music to jam out to while you hack at [Every Noise at Once](https://everynoise.com/engenremap.html) (HT: Jeanette Clark)
